/**
* \file FileSystem.h
*
* \brief Path resolution utilities for loading resources at runtime.
*
* Copyright https://learnopengl.com/
*/

#ifndef FILESYSTEM_H
#define FILESYSTEM_H

#include <string>
#include <cstdlib>
#include <root_directory.h> // This is a configuration file generated by CMake.

// TODO use std::filesystem
/**
* \class FileSystem
*
* \brief Utilities for resolving file paths relative to the project root.
*
* Provides platform-independent path resolution for loading resources (shaders,
* volume data, etc.) at runtime. The class automatically determines the project
* root directory from CMake-generated configuration and resolves relative paths
* accordingly.
*
* The root directory is determined by:
* 1. The LOGL_ROOT_PATH environment variable (if set)
* 2. The logl_root constant from root_directory.h (generated by CMake)
* 3. A relative path from the binary location (fallback)
*
* This allows the same code to work whether run from the build directory or
* after installation.
*
* @see root_directory.h for CMake-generated root path constant.
* @see Shader for loading shader files using FileSystem::getPath.
*/
class FileSystem
{
private:
  typedef std::string (*Builder) (const std::string& path);

public:
  /**
  * Resolves a relative path to an absolute path based on the project root.
  * @param path Relative path from project root (e.g., "src/shaders/volume.frag").
  * @return Absolute path to the file.
  */
  static std::string getPath(const std::string& path)
  {
    static std::string(*pathBuilder)(std::string const &) = getPathBuilder();
    return (*pathBuilder)(path);
  }

private:
  /**
  * Gets the project root directory.
  * @return Root directory path as a const reference.
  */
  static std::string const & getRoot()
  {
    static char const * envRoot = getenv("LOGL_ROOT_PATH");
    static char const * givenRoot = (envRoot != nullptr ? envRoot : logl_root);
    static std::string root = (givenRoot != nullptr ? givenRoot : "");
    return root;
  }

  /**
  * Gets the appropriate path builder function based on root availability.
  * @return Function pointer to path builder.
  */
  static Builder getPathBuilder()
  {
    if (getRoot() != "")
      return &FileSystem::getPathRelativeRoot;
    else
      return &FileSystem::getPathRelativeBinary;
  }

  /**
  * Builds absolute path from root directory.
  * @param path Relative path from project root.
  * @return Absolute path.
  */
  static std::string getPathRelativeRoot(const std::string& path)
  {
    return getRoot() + std::string("/") + path;
  }

  /**
  * Builds path relative to binary location (fallback).
  * @param path Relative path from project root.
  * @return Path relative to binary.
  */
  static std::string getPathRelativeBinary(const std::string& path)
  {
    return "../../../" + path;
  }


};

// FILESYSTEM_H
#endif
