/**
* \file FileSystem.h
*
* \brief Path resolution utilities for loading resources at runtime.
*
* Copyright https://learnopengl.com/
*/

#ifndef FILE_SYSTEM_H
#define FILE_SYSTEM_H

#include <root_directory.h>

#include <filesystem>
#include <string>

/**
* \namespace FileSystem
*
* \brief Utilities for resolving file paths relative to the project root.
*
* Provides platform-independent path resolution for loading resources (shaders,
* volume data, etc.) at runtime. The namespace uses the CMake-generated root
* directory constant to resolve relative paths accordingly.
*
* The root directory is determined by:
* 1. The logl_root constant from root_directory.h (generated by CMake)
* 2. A relative path from the binary location (fallback)
*
* This allows the same code to work whether run from the build directory or
* after installation.
*
* @see root_directory.h for CMake-generated root path constant.
* @see Shader for loading shader files using FileSystem::GetPath.
*/
namespace FileSystem
{
    /**
    * Resolves a relative path to an absolute path based on the project root.
    * @param relativePath Relative path from project root (e.g., "src/shaders/volume.frag").
    * @return Absolute path to the file as a string.
    */
    inline std::string GetPath(const std::string& relativePath)
    {
        if (logl_root != nullptr && logl_root[0] != '\0')
        {
            return (std::filesystem::path{logl_root} / relativePath).string();
        }
        else
        {
            return (std::filesystem::path{"../../.."} / relativePath).string();
        }
    }
}

#endif
